# Generated by Django 4.1.5 on 2023-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_remove_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
