# Generated by Django 4.1.5 on 2023-02-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
